@localhost = http://localhost:4004/odata/v4/main
@id=0f60ad28-8757-49f8-a7ab-84f581cc6d74

GET {{localhost}}/Customers
Content-Type: application/json

###

POST {{localhost}}/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "João",
    "lastName": "Moraes",
    "email": "joao.moraes@numenit.com"
}

###

DELETE {{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

# TEORIA = Essa ação de atualizar, por padrão, atualiza todos os campos, exceto a chave.
# PRATICA = Está funcionando, trocando apenas o campo indicado, mas na duvida, NÃO FAZER
PUT {{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Zé"
}

###

# Essa ação de atualizar, por padrão, atualiza apenas os campos informados.
PATCH {{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Jededaia"
}

###

GET {{localhost}}/Customers?$filter=endswith(firstName, '-1234')
Content-Type: application/json