@localhost=http://localhost:4004/odata/v4/main
@id=518ac8eb-b57e-4962-b2ee-df9eaa94635e
@customerId=0f60ad28-8757-49f8-a7ab-84f581cc6d74
@productId=9ae2fa58-7e40-4a1b-b893-a868c0536827

GET {{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items($expand=product)
Content-Type: application/json

###

POST {{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    // Aqui a nomenclatrua do campo deve ser exatamente igual ao definido no modelo NomeDaColunaPai_NomeDoCampoFilho
    "customer_id": "{{customerId}}",
    "totalAmount": 15,
    "items": [
        {
            "id": "59d903ae-bdcd-4f70-bc24-58b137db2cf4",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "688ebc37-0da1-4a02-a474-ab34990e9845",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE {{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT {{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "joaomoraes"
}

###

# Buscar todos os pedido menores ou iguais
GET {{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000

###

# Expandindo os itens, prodoutos e customers
GET {{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000&$expand=items($expand=product),customer

###

# Expandindo os itens, pordoutos e customers e filtrando
GET {{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2000000&$expand=items($expand=product;$filter=quantity le 30),customer

###

# Selecionar somente customer e id do sales order header
GET {{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)

###

# Descobrindo a qtd de registros
GET {{localhost}}/SalesOrderHeaders/$count

###

# Paginando os registros
GET {{localhost}}/SalesOrderHeaders?$skip=10&$top=5